DoctorWebForum/Entities/Feedback.cs
namespace DoctorWebForum.Entities
{
    public class Feedback
    {
        public int Id { get; set; }
        public string? Content { get; set; }
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }
        public int? ChildId { get; set; }
        public int Level { get; set; }
        public bool IsRoot { get; set; }
        public int PostId { get; set; }
        public bool IsDelete { get; set; }
        public Post Post { get; set; }
    }
}

DoctorWebForum/Controllers/FeedbacksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoctorWebForum.Data;
using DoctorWebForum.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Authorization;

namespace DoctorWebForum.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FeedbacksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly Post _post;
        private readonly string UserId;

        public FeedbacksController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, Post post)
        {
            _context = context;
            _userManager = userManager;
            _post = post;
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Feedback.Include(x => x.Post).Include(x=>x.User).AsQueryable();
            return View( await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            var feedback = await _context.Feedback
                .Include(x => x.Post)
                .Include(x=>x.User)
                .Where(x => x.Id == id)
                .FirstOrDefaultAsync();
            if (feedback == null) return NotFound();

            return View(feedback);
        }

        public IActionResult Create()
        {
            ViewData["PostId"] = new SelectList(_context.Post, "Id", "Id");
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Feedback feedback)
        {
            ViewData["PostId"] = new SelectList(_context.Post, "Id", "Id", feedback.PostId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", feedback.UserId);

            _context.Add(feedback);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var feedback = await _context.Feedback.FindAsync(id);    
            if (feedback == null) return NotFound();

            ViewData["PostId"] = new SelectList(_context.Post, "Id", "Id", feedback.PostId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Name", feedback.UserId);
            return View(feedback);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Feedback feedback)
        {
            if (feedback == null) return NotFound();

            _context.Update(feedback);

            await _context.SaveChangesAsync();

            ViewData["PostId"] = new SelectList(_context.Post, "Id", "Id", feedback.PostId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", feedback.UserId);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id) 
        {
            var feedback = await _context.Feedback
                .Include(x => x.User)
                .Include(x=>x.Post)
                .Where(x => x.Id == id)
                .FirstOrDefaultAsync();

            if (feedback == null) return NotFound();

            ViewData["PostId"] = new SelectList(_context.Post, "Id", "Id", feedback.PostId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Name", feedback.UserId);

            return View(feedback);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var feedback = await _context.Feedback.FindAsync(id);
            if (feedback != null)
            {
                _context.Feedback.Remove(feedback);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

DoctorWebForum/Controllers/UserController.cs
using DoctorWebForum.DTOs;
using DoctorWebForum.Interfaces;
using DoctorWebForum.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;

namespace DoctorWebForum.Controllers
{
    public class UserController : Controller
    {

        private readonly ILogger<UserController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserService _userService;

        public UserController(ILogger<UserController> logger, IUserService userService, UserManager<ApplicationUser> userManager)
        {
            _userService = userService;
            _logger = logger;
            _userManager = userManager;
        }

        public async Task<IActionResult> Member(string sTerm = "", int qualificationId = 0, int experienceId = 0)
        {
            IEnumerable<ApplicationUser> users = await _userService.GetUsers(sTerm, qualificationId, experienceId);
            IEnumerable<Qualification> qualifications = await _userService.Qualifications();
            IEnumerable<Experience> experiences = await _userService.Experiences();
            UserDisplayModel userModel = new UserDisplayModel
            {
                Users = users,
                Qualifications = qualifications,
                STerm = sTerm,
                QualificationId = qualificationId,
                Experiences = experiences,
                ExperienceId = experienceId,
                
            };
            return View(userModel);
        }

        public async Task<IActionResult> Details(string id)
        {
            var currentUser = _userManager.GetUserId(this.User);

            var user = await _userService.GetUserById(id);

            user.currentId = currentUser;

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
    }
}

DoctorWebForum/Views/Shared/_Feedback.cshtml
@using DoctorWebForum.DTOs;
@model FeedbackModel;
@{
    var something = Model;
}

<h2>@ViewBag.Data</h2>

<form asp-controller="Home" asp-action="CreateFeedback" method="post">
    @Html.AntiForgeryToken()
    <div class="bp-ac-form-cotainer">

        <div class="ac-reply-avatar">
            @*<img src="~/Uploads/@Model.User.ProfilePicture"
                 class="avatar user-2-avatar avatar-150 photo"
                 width="150" height="150"
                 alt="">*@
        </div>

        <div class="ac-reply-content" style="display:flex">
            <div class="ac-textarea">
                <label for="ac-input-194622"
                       class="bp-screen-reader-text">
                    Comment
                </label>
                <textarea rows="1" cols="50" contenteditable="true"
                          id="ac-input-194622"
                          class="ac-input bp-suggestions"
                          name="Content" style="resize: none;height: auto"></textarea> 
                <input type="hidden" asp-for="PostId" name="PostId" />
                <div id="ac-reply-attachments-194622"
                     class="ac-reply-attachments">
                </div>
            </div>
            <input type="submit" 
                   class="button" value="Post" />
            @*<button type="button"
                    class="ac-reply-cancel">
                Cancel
            </button>*@
        </div>

    </div>
</form>

@*<form asp-controller="Feedbacks" asp-action="Create" method="post" id="ac-form" asp-route-id="@Model.Id"
      class="ac-form events-initiated root"
      style="display: none;">

    <div class="bp-ac-form-cotainer">

        <div class="ac-reply-avatar">
            <img src="https://vuainnhanh.com/wp-content/uploads/2023/02/logo-chu-thap-do.png"
                 class="avatar user-2-avatar avatar-150 photo"
                 width="150" height="150"
                 alt="">
        </div>

        <div class="ac-reply-content">
            <div class="ac-textarea">
                <label for="ac-input-194622"
                       class="bp-screen-reader-text">
                    Comment
                </label>
                <textarea rows="1" contenteditable="true"
                     id="ac-input-194622"
                     class="ac-input bp-suggestions"
                          name="Content" style="resize: none;height: auto"></textarea>  input

                <div id="ac-reply-attachments-194622"
                     class="ac-reply-attachments">
                </div>
            </div>
            <input type="hidden"
                   name="Content"
                   >

            <input type="submit"
                   class="button" value="Post" />
            <button type="button"
                    class="ac-reply-cancel">
                Cancel
            </button>
        </div>

    </div>
</form>*@

DoctorWebForum/Views/Shared/_FeedbackReply.cshtml
<form action="" method="post" id="ac-form-194574"
      class="ac-form events-initiated" style="display: block;">

    <div class="bp-ac-form-cotainer">

        <div class="ac-reply-avatar">
            <img src=""
                 class="avatar user-2-avatar avatar-150 photo" width="150" height="150" alt="Profile photo of John">
        </div>

        <div class="ac-reply-content">
            <div class="ac-textarea">
                <label for="ac-input-194574" class="bp-screen-reader-text">
                    Comment
                </label>
                <div contenteditable="true" id="ac-input-194574" class="ac-input bp-suggestions"
                     name="ac_input_194574"></div>


                <input type="hidden" name="comment_form_id" value="194574">

                <input type="submit" name="ac_form_submit" value="Post"><input type="hidden"
                                                                               id="_wpnonce_new_activity_comment" name="_wpnonce_new_activity_comment"
                                                                               value="1f2b66777e"><input type="hidden" name="_wp_http_referer"
                                                                                                         value="/online-communities/wp-admin/admin-ajax.php">&nbsp; <button type="button"
                                                                                                                                                                            class="ac-reply-cancel">
                    Cancel
                </button>
            </div>

        </div>
</form>

DoctorWebForum/Views/Shared/_PostCard.cshtml
@using DoctorWebForum.DTOs;
@model PostDisplayModel
@{
    var feedback = new FeedbackModel();
    feedback.PostId = Model.Id;
}

<li class="activity activity_update activity-item date-recorded-1683607555"
    id="activity"
    data-bp-timestamp="1683607555"
    data-bp-activity="{&quot;id&quot;:194622,&quot;can_edit_privacy&quot;:true,&quot;album_id&quot;:0,&quot;group_id&quot;:0,&quot;group_name&quot;:&quot;&quot;,&quot;folder_id&quot;:0,&quot;content&quot;:&quot;<p>\u00e1dasd<\/p>&quot;,&quot;item_id&quot;:0,&quot;object&quot;:&quot;activity&quot;,&quot;privacy&quot;:&quot;public&quot;,&quot;group_avatar&quot;:&quot;&quot;,&quot;link_image_index_save&quot;:&quot;&quot;,&quot;profile_video&quot;:true,&quot;group_video&quot;:true,&quot;profile_media&quot;:true,&quot;group_media&quot;:true,&quot;profile_document&quot;:true,&quot;group_document&quot;:true}">

    @if (@Model.currentUserId == @Model.UserId)
    {
        <div class="bb-activity-more-options-wrap action">
            <span class="bb-activity-more-options-action" data-balloon-pos="up" data-balloon="More Options">
                <i class="bb-icon-f bb-icon-ellipsis-h"></i>
            </span>
            <div class="bb-activity-more-options">
                <div class="generic-button">
                    <a style="padding:0 0 0 15px" id="report-content-activity-194593" class="button item-button bp-secondary-action report-content" >
                        @*<span class="bp-screen-reader-text">Edit</span>
                        <span class="report-label">Edit</span>*@
                        <form asp-controller="Home" asp-action="EditPost" style="margin:0;">
                            <input type="submit" value="Edit" asp-controller="Home" asp-action="EditPost" asp-route-id="@Model.Id" style="background: #fff; color:black; padding:0; border:none; font-weight:400; font-size:13px;" />
                        </form>
                    </a>
                </div>
                <div class="generic-button">
                    <a style="padding:0 0 0 15px" class="button item-button bp-secondary-action delete-activity confirm">
                        @*<span class="bp-screen-reader-text">Delete</span>
                    <span class="delete-label">Delete</span>*@
                        <form asp-controller="Home" asp-action="DeletePost" style="margin:0;">
                            <input type="submit" value="Delete" asp-controller="Home" asp-action="DeletePost" asp-route-id="@Model.Id" style="background: #fff; color:black; padding:0; border:none; font-weight:400; font-size:13px;" />
                        </form>
                    </a>
                </div>
            </div>
        </div>
    }
    <div class="bp-activity-head">
        <div class="activity-avatar item-avatar">
            <a asp-controller="User" asp-action="Details" asp-route-id="@Model.UserId">
                <img src="~/Uploads/@Model.User.ProfilePicture"
                     class="avatar user-2-avatar avatar-300 photo"
                     width="300" height="300"
                     alt="Profile photo of Admin" style="height:35px;">
            </a>
        </div>

        <div class="activity-header" style="margin-top: -0.2rem;">
            <p>
                <a asp-controller="User" asp-action="Details" asp-route-id="@Model.User.Id">@Model.User.Name</a>
                posted an update
                <a href=""
                   class="view activity-time-since">
                    <span class="time-since">
                        32 minutes
                        ago
                    </span>
                </a>
            </p>
            <p class="activity-date">
                <a href="">
                    a
                    second
                    ago
                </a>
            </p>
            <div class="bb-media-privacy-wrap">
                <span class="bp-tooltip privacy-wrap"
                      data-bp-tooltip-pos="up"
                      data-bp-tooltip="Public">
                    <span class="privacy selected public"></span>
                </span>
                <ul class="activity-privacy">
                    <li data-value="public"
                        class="public selected">Public</li>
                    <li data-value="loggedin"
                        class="loggedin ">All Members</li>
                    <li data-value="friends"
                        class="friends ">My Connections</li>
                    <li data-value="onlyme" class="onlyme ">
                        Only Me
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="activity-content ">
        <div class="activity-inner ">
            <p>@Model.Title</p>
        </div>
        <div class="activity-inner ">
            <p>@Model.Description</p>
        </div>

        <div class="activity-state  ">
            <a href="javascript:void(0);"
               class="activity-state-likes">
                <span class="like-text hint--bottom hint--medium hint--multiline"
                      data-hint="">
                </span>
            </a>
            <span class="ac-state-separator">·</span>
            <a href="#" class="activity-state-comments">
                <span class="comments-count">
                    0 Comment
                </span>
            </a>
        </div>
    </div>

    <div class="bp-generic-meta activity-meta action">
        <div class="generic-button">
            <a href=""
               class="button fav bp-secondary-action"
               aria-pressed="false">
                <span class="bp-screen-reader-text">Like</span>
                <span class="like-count">Like</span>
            </a>
        </div>
        <div class="generic-button">
            <a id="acomment-comment" class="button acomment-reply bp-primary-action">
                <span class="bp-screen-reader-text">Comment</span>
                <span class="comment-count">Comment</span>
            </a>
        </div>
    </div>

    <div class="activity-comments">
        <ul>
            @foreach (var feedbacks in Model.Feedbacks)
            {
                <li id="acomment" class=" comment-item">
                    @if (Model.currentUserId == @feedbacks.UserId)
                    {
                        <div class="bb-activity-more-options-wrap action">
                            <span class="bb-activity-more-options-action" data-balloon-pos="up" data-balloon="More Options">
                                <i class="bb-icon-f bb-icon-ellipsis-h"></i>
                            </span>
                            <div class="bb-activity-more-options">
                                @*<div class="generic-button">
                                    <a class="delete acomment-delete confirm bp-secondary-action" rel="nofollow" style="padding: 0 0 0 15px">
                                        <form asp-controller="Home" asp-action="EditFeedback" style="margin:0;padding:0">
                                            <input type="submit" value="Edit" asp-controller="Home" asp-action="EditFeedback" asp-route-id="@feedbacks.Id" style="background: #fff; color:black; padding:0; border:none; font-weight:400; font-size:13px;" />
                                        </form>
                                    </a>
                                </div>*@
                                <div class="generic-button">
                                    <a class="delete acomment-delete confirm bp-secondary-action" rel="nofollow" style="padding: 0 0 0 15px">
                                        <form asp-controller="Home" asp-action="DeleteFeedback" style="margin:0;padding:0">
                                            <input type="submit" value="Delete" asp-controller="Home" asp-action="DeleteFeedback" asp-route-id="@feedbacks.Id" style="background: #fff; color:black; padding:0; border:none; font-weight:400; font-size:13px;" />
                                        </form>
                                    </a>
                                </div>
                            </div>
                        </div>

                    }
                    <div class="acomment-avatar item-avatar">
                        <a asp-controller="User" asp-action="Details" asp-route-id="@feedbacks.User.Id">
                            <img src="~/Uploads/@feedbacks.User.ProfilePicture" style="height:35px;" class="avatar user-4-avatar avatar-150 photo" width="150" height="150" alt="">
                        </a>
                    </div>

                    <div class="acomment-meta">
                        <a class="author-name" asp-controller="User" asp-action="Details" asp-route-id="@feedbacks.User.Id">@feedbacks.User.Name</a>
                    </div>

                    <div class="acomment-content">
                        <p><span>@feedbacks.Content</span></p>
                    </div>

                    <div class="bp-generic-meta activity-meta action"><div class="generic-button"><a class="acomment-reply bp-primary-action" id="acomment-reply-194597-from-194599" href="#acomment-194599" aria-expanded="false">Reply</a></div></div>
                </li>
            }
        </ul>
        <partial name="_Feedback" model="feedback" />
        @*<partial name="_FeedbackReply"/>*@
    </div>
</li>



@*<div class="bb-activity-more-options-wrap action">
    <span class="bb-activity-more-options-action"
    data-balloon-pos="up"
    data-balloon="More Options">
    <i class="bb-icon-f bb-icon-ellipsis-h"></i>
    </span>
    <div class="bb-activity-more-options">
    <div class="generic-button">
    <a href="#"
    class="button edit edit-activity bp-secondary-action bp-tooltip"
    title="Edit Activity">
    <span class="bp-screen-reader-text">
    Edit
    Activity
    </span><span class="edit-label">Edit</span>
    </a>
    </div>
    <div class="generic-button">
    <a href=""
    class="button item-button bp-secondary-action delete-activity confirm">
    <span class="bp-screen-reader-text">Delete</span><span class="delete-label">Delete</span>
    </a>
    </div>
    </div>
    </div>*@

@*<div class="bb-activity-more-options-wrap action">
                <span class="bb-activity-more-options-action" data-balloon-pos="up" data-balloon="More Options">
                <i class="bb-icon-f bb-icon-ellipsis-h"></i>
                </span>
                <div class="bb-activity-more-options">
                <div class="generic-button">
                <a id="report-content-activity_comment" href="#content-report" class="button item-button bp-secondary-action report-content"  data-bp-content-type="activity_comment" data-bp-nonce="eb3f3122ad" reported_type="Comment"><span class="bp-screen-reader-text">Report Comment</span><span class="report-label">Report Comment</span></a></div> <div class="generic-button"><a class="delete acomment-delete confirm bp-secondary-action" rel="nofollow" href="https://demos.buddyboss.com/online-communities/activity-feed/delete/194599/?cid=194599&amp;_wpnonce=5f3d318edd">Delete</a></div></div></div>*@

@*<ul>

                <li id="acomment" class=" comment-item" >

                <div class="bb-activity-more-options-wrap action"><span class="bb-activity-more-options-action" data-balloon-pos="up" data-balloon="More Options"><i class="bb-icon-f bb-icon-ellipsis-h"></i></span><div class="bb-activity-more-options"><div class="generic-button"><a class="delete acomment-delete confirm bp-secondary-action" rel="nofollow" href="https://demos.buddyboss.com/online-communities/activity-feed/delete/194600/?cid=194600&amp;_wpnonce=5f3d318edd">Delete</a></div></div></div>
                <div class="acomment-avatar item-avatar">
                <a href="">
                <img src="https://demos.buddyboss.com/online-communities/wp-content/sandbox188778-uploads/avatars/2/621e2ce4392dd-bpthumb.png" class="avatar user-2-avatar avatar-150 photo" width="150" height="150" alt="Profile photo of John">
                </a>
                </div>

                <div class="acomment-meta">

                <a class="author-name" href="https://demos.buddyboss.com/online-communities/members/john/">John</a> <a href="https://demos.buddyboss.com/online-communities/activity-feed/p/194597/#acomment-194600" class="activity-time-since"><time class="time-since" datetime="2021-07-01 06:24:17" data-bp-timestamp="1625120657">a year ago</time></a>
                </div>

                <div class="acomment-content">
                <p><span>Our trip from last summer</span></p>

                </div>

                <div class="bp-generic-meta activity-meta action"><div class="generic-button"><a class="acomment-reply bp-primary-action" id="acomment-reply-194597-from-194600" href="#acomment-194600" aria-expanded="false">Reply</a></div></div>
                </li>
                </ul>*@