DoctorWebForum/Entities/Post.cs
namespace DoctorWebForum.Entities
{
    public class Post
    {
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public string? HtmlContent { get; set; }
        public string UserId { get; set; }
        public  ApplicationUser User { get; set; }
        public bool IsDelete { get; set; }
        public ICollection<Feedback> Feedbacks { get; set; }
    }
}

DoctorWebForum/Controllers/AccountsController.cs
using DoctorWebForum.Constant;
using DoctorWebForum.Data;
using DoctorWebForum.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Scripting;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using System.Text;

namespace DoctorWebForum.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AccountsController : Controller
    {
        private readonly ILogger<UserController> _logger;

        private readonly ApplicationDbContext _context;
        public AccountsController(ApplicationDbContext context, ILogger<UserController> logger)
        {
            _context = context;
            _logger = logger;
        }
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ApplicationUser
                .Include(x => x.Qualification)
                .Include(x => x.Experience)
                .Where(x => !x.IsDelete)
                .AsQueryable();

            return View( await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(string? id)
        {
            var user = await _context.ApplicationUser
                .Include(x => x.Qualification)
                .Include(x => x.Experience)
                .Where(x => x.Id == id)
                .FirstOrDefaultAsync();

            if (user == null) return NotFound();

            return View(user);
        }

        public IActionResult Create()
        {
            ViewData["QualificationId"] = new SelectList(_context.Qualification, "Id", "Name");
            ViewData["ExperienceId"] = new SelectList(_context.Experience, "Id", "Years");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ApplicationUser applicationUser)
        {
            ViewData["QualificationId"] = new SelectList(_context.Qualification, "Id", "Id", applicationUser.QualificationId);
            ViewData["ExperienceId"] = new SelectList(_context.Experience, "Id", "Id", applicationUser.ExperienceId);

            //string password = applicationUser.PasswordHash;

            //string hashedPassword = HashPassword(password);

            _context.Add(applicationUser);

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(string? id)
        {
            
            var applicationUser = await _context.ApplicationUser.FindAsync(id);

            if (applicationUser == null) return NotFound();

            ViewData["QualificationId"] = new SelectList(_context.Qualification, "Id", "Name", applicationUser.QualificationId);
            ViewData["ExperienceId"] = new SelectList(_context.Experience, "Id", "Years", applicationUser.ExperienceId);
            return View(applicationUser);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ApplicationUser applicationUser)
        {

            if (applicationUser == null) return NotFound();

            //string password = applicationUser.PasswordHash;

            //string hashedPassword = HashPassword(password);

            _context.Update(applicationUser);

            await _context.SaveChangesAsync();

            ViewData["QualificationId"] = new SelectList(_context.Qualification, "Id", "Name", applicationUser.QualificationId);
            ViewData["ExperienceId"] = new SelectList(_context.Experience, "Id", "Years", applicationUser.ExperienceId);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string? id)
        {
            var applicationUser = await _context.ApplicationUser
                .Include(x => x.Qualification)
                .Include(x => x.Experience)
                .Where(x => x.Id == id)
                .FirstOrDefaultAsync();

            if (applicationUser == null) return NotFound();

            ViewData["QualificationId"] = new SelectList(_context.Qualification, "Id", "Name", applicationUser.QualificationId);
            ViewData["ExperienceId"] = new SelectList(_context.Experience, "Id", "Years", applicationUser.ExperienceId);

            return View(applicationUser);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string? id)
        {
            var applicationUser = await _context.ApplicationUser.FindAsync(id);

            if (applicationUser != null)
            {
                applicationUser.IsDelete = true;
                _context.Update(applicationUser);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //public static string HashPassword(string password)
        //{
        //    using (var sha256 = SHA256.Create())
        //    {
        //        // Convert the password to bytes
        //        byte[] passwordBytes = Encoding.UTF8.GetBytes(password);

        //        // Compute the hash
        //        byte[] hashBytes = sha256.ComputeHash(passwordBytes);

        //        // Convert the hash to a string
        //        string hash = BitConverter.ToString(hashBytes).Replace("-", "").ToLower();

        //        return hash;
        //    }
        //}



        //public string HashPassWord(string password)
        //{
        //    SHA256 hash = SHA256.Create();

        //    var passwordBytes = Encoding.Default.GetBytes(password);

        //    var hashedPassword = hash.ComputeHash(passwordBytes);

        //    return Convert.ToHexString(hashedPassword);
        //}

    }
}

DoctorWebForum/Controllers/FeedbacksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoctorWebForum.Data;
using DoctorWebForum.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Authorization;

namespace DoctorWebForum.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FeedbacksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly Post _post;
        private readonly string UserId;

        public FeedbacksController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, Post post)
        {
            _context = context;
            _userManager = userManager;
            _post = post;
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Feedback.Include(x => x.Post).Include(x=>x.User).AsQueryable();
            return View( await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            var feedback = await _context.Feedback
                .Include(x => x.Post)
                .Include(x=>x.User)
                .Where(x => x.Id == id)
                .FirstOrDefaultAsync();
            if (feedback == null) return NotFound();

            return View(feedback);
        }

        public IActionResult Create()
        {
            ViewData["PostId"] = new SelectList(_context.Post, "Id", "Id");
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Feedback feedback)
        {
            ViewData["PostId"] = new SelectList(_context.Post, "Id", "Id", feedback.PostId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", feedback.UserId);

            _context.Add(feedback);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var feedback = await _context.Feedback.FindAsync(id);    
            if (feedback == null) return NotFound();

            ViewData["PostId"] = new SelectList(_context.Post, "Id", "Id", feedback.PostId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Name", feedback.UserId);
            return View(feedback);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Feedback feedback)
        {
            if (feedback == null) return NotFound();

            _context.Update(feedback);

            await _context.SaveChangesAsync();

            ViewData["PostId"] = new SelectList(_context.Post, "Id", "Id", feedback.PostId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", feedback.UserId);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id) 
        {
            var feedback = await _context.Feedback
                .Include(x => x.User)
                .Include(x=>x.Post)
                .Where(x => x.Id == id)
                .FirstOrDefaultAsync();

            if (feedback == null) return NotFound();

            ViewData["PostId"] = new SelectList(_context.Post, "Id", "Id", feedback.PostId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Name", feedback.UserId);

            return View(feedback);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var feedback = await _context.Feedback.FindAsync(id);
            if (feedback != null)
            {
                _context.Feedback.Remove(feedback);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

DoctorWebForum/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoctorWebForum.Data;
using DoctorWebForum.Entities;
using Microsoft.AspNetCore.Identity;
using DoctorWebForum.DTOs;
using DoctorWebForum.Interfaces;
using Microsoft.Extensions.Hosting;
using DoctorWebForum.Constant;
using Microsoft.AspNetCore.Authorization;

namespace DoctorWebForum.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly string UserId;
        private readonly IPostService _postService;
        public PostsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IPostService postService)
        {
            _context = context;
            _userManager = userManager;
            _postService = postService;
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Post
                .Include(p => p.User)
                .Where(x => !x.IsDelete && !x.User.IsDelete);
                //.Where(x => !x.User.IsDelete);

            //(ICollection<Feedback>)(x.Feedbacks != null ? x.Feedbacks.Where(p => !p.User.IsDelete) : null)

            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            var post = await _context.Post.Include(p => p.User).Where(x => x.Id == id).FirstOrDefaultAsync();

            if (post == null) return NotFound();

            return View(post);
        }

        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Post post)
        {
            _context.Add(post);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", post.UserId);
            return View(post);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var post = await _context.Post.FindAsync(id);

            if (post == null) return NotFound();

            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Name", post.UserId);
            return View(post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Post post)
        {
            _context.Update(post);
            await _context.SaveChangesAsync();

            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Name", post.UserId);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var post = await _context.Post.Include(p => p.User).Where(x => x.Id == id).FirstOrDefaultAsync();

            if (post == null) return NotFound();


            ViewData["UserId"] = new SelectList(_context.ApplicationUser, "Id", "Name", post.UserId);

            return View(post);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Post.FindAsync(id);

            if (post != null)
            {
                post.IsDelete = true;
                _context.Update(post);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

DoctorWebForum/Views/Posts/Create.cshtml
@model DoctorWebForum.Entities.Post

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="HtmlContent" class="control-label"></label>
                <input asp-for="HtmlContent" class="form-control" />
                <span asp-validation-for="HtmlContent" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DoctorWebForum/Views/Posts/Delete.cshtml
@model DoctorWebForum.Entities.Post

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DoctorWebForum/Views/Posts/Details.cshtml
@model DoctorWebForum.Entities.Post

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index" class="btn btn-outline-dark">Back to List</a>
</div>

DoctorWebForum/Views/Posts/Edit.cshtml
@model DoctorWebForum.Entities.Post

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            @*<div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="HtmlContent" class="control-label"></label>
                <input asp-for="HtmlContent" class="form-control" />
                <span asp-validation-for="HtmlContent" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DoctorWebForum/Views/Posts/Index.cshtml
@model IEnumerable<DoctorWebForum.Entities.Post>


<style>
    /*body {
        width: 100vw;
        height: 100vh;
        font-family: poppins, sans-serif;
        font-size: 0.8 8rem;
        background: #f6f6f9;
        user-select: none;
        overflow -x: hidden;
        color: #363949;
    }
*/
    .container {
        display: grid;
        width: 96%;
        margin: 0 auto;
        gap: 1.8rem;
        grid-template-columns: 14rem auto 23rem;
    }

    h1 {
        font-weight: 800;
        font-size: 1.8rem;
    }

    h3 {
        font-size: 0.87rem;
    }

    .aside {
        height: 100vh;
    }

        .aside .top {
            /*display: flex;
            align-items: center;
            justify-content: center;*/
            margin-top: 1.4rem;
        }

        .aside .logo {
            display: flex;
            gap: 0.8rem;
        }

            .aside .logo #img {
                width: 2rem;
                height: 2rem;
            }

        .aside .close {
            display: none;
        }

        .aside .sidebar {
            display: flex;
            flex-direction: column;
            height: 86vh;
            position: relative;
            top: 3rem;
        }

        .aside h3 {
            font-weight: 500;
        }

        .aside .sidebar a {
            display: flex;
            color: #7d8da1;
            margin-left: 2rem;
            gap: 1rem;
            align-items: center;
            position: relative;
            height: 3.7rem;
            transition: all 300ms ease;
        }

            .aside .sidebar a span {
                font-size: 1.6rem;
                transition: all 300ms ease;
            }

            .aside .sidebar a:last-child {
                position: absolute;
                bottom: 2rem;
                width: 100%;
            }

            .aside .sidebar a.active {
                background: rgba(132, 139, 200, 0.18);
                color: #7380ec;
                margin-left: 0;
            }

                .aside .sidebar a.active::before {
                    content: '';
                    width: 6px;
                    height: 100%;
                    background: #7380ec;
                }

                .aside .sidebar a.active span {
                    color: #7380ec;
                    margin-left: calc(1rem - 3px);
                }

            .aside .sidebar a:hover {
                color: #7380ec;
            }

                .aside .sidebar a:hover span {
                    margin-left: 1rem;
                }

        .aside .sidebar .message-count {
            background: #ff7782;
            color: #fff;
            padding: 2px 10px;
            font-size: 11px;
            border-radius: 0.4rem;
            ;
        }

    .main .recent-orders {
        margin-top: 2rem;
    }

        .main .recent-orders h2 {
            margin-bottom: 0.8rem;
        }

        .main .recent-orders .table {
            background: #fff;
            width: 50rem;
            border-radius: 2rem;
            text-align: center;
            box-shadow: 0 2rem 3rem var(--color-light);
            transition: all 300ms ease;
            border:none;
        }
            .main .recent-orders .table:hover {
                box-shadow: none;
            }

    .main .table .tbody td {
        /*height: 2.8rem;*/
        border-bottom: 1px solid rgba(132, 139, 200, 0.18);
        /*color: #a3bdcc;*/
    }

    .main .table .tbody tr:last-child td {
        border: none;
    }

    .main .recent-orders a {
        text-align: center;
        display: block;
        margin: 1rem auto;
        /*color: #7380ec;*/
    }

</style>


<div class="container">
    <aside class="aside">
        <div class="top">
            <div class="logo">
                <img id="img" src="https://vuainnhanh.com/wp-content/uploads/2023/02/logo-chu-thap-do.png" alt="">
            </div>
        </div>
        <div class="slidebar">
            <a asp-controller="Accounts" asp-action="Index">
                <span class="_mi _before bb-icon-l buddyboss bb-icon-user-friends-alt">Account</span>
                <h3>Account</h3>
            </a>
            <a asp-controller="Posts" asp-action="Index" class="active">
                <span class="_mi _before bb-icon-l bb-icon-poll-h">Posts</span>
                <h3>Posts</h3>
            </a>
            <a asp-controller="Feedbacks" asp-action="Index">
                <span class="_mi _before bb-icon-l buddyboss bb-icon-comment-square">Feedbacks</span>
                <h3>Feedbacks</h3>
            </a>
        </div>
    </aside>

    <main class="main">
        <h1>Dashoard</h1>
        <div class="date">
            <a asp-action="Create" class="btn btn-outline-dark">Create New</a>
        </div>

        <div class="recent-orders">
            <h2>Posts</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th style="text-align:center;font-weight:bold;">
                            @Html.DisplayNameFor(model => model.Id)
                        </th>
                        <th style="text-align:center;font-weight:bold;">
                            @Html.DisplayNameFor(model => model.Description)
                        </th>
                        <th style="text-align:center;font-weight:bold;">
                            @Html.DisplayNameFor(model => model.User)
                        </th>
                        <th style="text-align:center;font-weight:bold;">Actions</th>
                    </tr>
                </thead>
                <tbody class="tbody">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td >
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.User.Name)
                            </td>
                            <td style="display:flex;justify-content: center">
                                <a style="margin:0" asp-action="Edit" asp-route-id="@item.Id" class="_mi _before bb-icon-l buddyboss bb-icon-edit"> Edit </a> |
                                <a style="margin:0" asp-action="Details" asp-route-id="@item.Id" class="_mi _before bb-icon-l buddyboss bb-icon-newspaper"> Details </a> |
                                <a style="margin:0" asp-action="Delete" asp-route-id="@item.Id" class="_mi _before bb-icon-l buddyboss bb-icon-delete-tag"> Delete </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </main>
</div>